name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Copy Docker Compose file to EC2
      run: scp -o StrictHostKeyChecking=no -i ${{ secrets.AWS_KEY }} docker-compose.yml ubuntu@${{ secrets.AWS_HOST }}:/home/ubuntu/docker-compose.yml

    - name: Deploy to EC2
      run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_KEY }} ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            docker-compose -f /home/ubuntu/docker-compose.yml down
            docker-compose -f /home/ubuntu/docker-compose.yml up -d
        EOF

